### ISSUE TITLE
Modbus Rs485

### ISSUE THREAD

**Issue by kmsj13** [bres55/Smart-BMS-arduino-Reader#10]
There is a variant of smart bms with RS485 port, how can we interface it?

**Comment by xSaro** [comment]
with a uart->rs485 module ?

**Comment by kmsj13** [comment]
![IMG_20200603_152510](https://user-images.githubusercontent.com/13902782/83655168-a6f48c00-a5f0-11ea-8099-82168b4b5353.jpg)
Please see picture above. this is a version of Smart bms with UART and RS485,

**Comment by xSaro** [comment]
i am not sure if you search for the bms.xlsx file? This file show you the communication....

**Comment by bres55** [comment]
Suggest you look here for general type of information.
https://endless-sphere.com/forums/viewtopic.php?f=14&t=88676
