### ISSUE TITLE
Contact Please

### ISSUE THREAD

**Issue by Manna101** [bres55/Smart-BMS-arduino-Reader#11]
Hi 
Can I please have your number ? Im struggling to set everything up. I would like to implement this in my final year project for some extra marks for a more user friendly system. Won't bother you, just a few short questions.

**Comment by Manna101** [comment]
Or my number is +27832050412

**Comment by xSaro** [comment]
sorry i can not help. 
    Am Freitag, 5. Juni 2020, 00:14:42 MESZ hat Manna101 <notifications@github.com> Folgendes geschrieben:  
 
 


Hi
Can I please have your number ? Im struggling to set everything up. I would like to implement this in my final year project for some extra marks for a more user friendly system. Won't bother you, just a few short questions.

**Comment by bres55** [comment]
This is not how GitHub works.
Post issues connected with this Smart-BMS-arduino Reader. I and others will endeavour to help, if we can. 
Or.
Suggest you look here for general type of information.
https://endless-sphere.com/forums/viewtopic.php?f=14&t=88676
