### ISSUE TITLE
I want to use it for 14s BMS

### ISSUE THREAD

**Issue by Himanshujalan** [bres55/Smart-BMS-arduino-Reader#13]
I am trying to use it for 14s BMS by connecting Tx, Rx, Gnd but not able to fetch ay data. Can you help me in this?

**Comment by ForrestFire0** [comment]
If you are still working on this, I would suggest trying my library that allows you to define the cell count. It is also a library format so you don't need to paste this mess of functions.

https://github.com/ForrestFire0/GenericBMSArduino

**Comment by bres55** [comment]
Looks like ForrestFire0 , has your answer.
