### ISSUE TITLE
Bluetooth Communication

### ISSUE THREAD

**Issue by Manna101** [bres55/Smart-BMS-arduino-Reader#9]
Im going to try to connect via Bluetooth to BMS to receive data, any tips before I begin ?

**Comment by xSaro** [comment]
this is my first post. But you have to set the PIN for Serial RX and TX. What kind of Board are you using ? Sorry for my english!

**Comment by xSaro** [comment]
or Uncomment the Code. From line 11 -13...
    #include <SoftwareSerial.h>                   //  un rem
    SoftwareSerial MySoftSerial(10, 11); // RX, TX  //  un rem
    #define MySerial MySoftSerial                    //  change MySerial

**Comment by bres55** [comment]
Suggest you look here for general type of information. 
https://endless-sphere.com/forums/viewtopic.php?f=14&t=88676
